name: BUILD_MEDIA_FFMPEG

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # ANDROID_NDK: "21.4.7075529"
      ANDROID_NDK: "26.3.11579264"
      MEDIA3: "release-1.5.0-alpha01"
      FFMPEG: "release/6.0"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Gradle
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip -qq commandlinetools-linux-7583922_latest.zip
        mkdir -p android-sdk/cmdline-tools && mv cmdline-tools $_/latest
        export ANDROID_HOME=$PWD/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export NDK_PATH=$ANDROID_HOME/ndk/$ANDROID_NDK
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        echo y | sdkmanager --update >> log.txt
        echo y | sdkmanager --install "ndk;$ANDROID_NDK" >> log.txt
        git clone -b $MEDIA3 https://github.com/androidx/media
        echo 'use media3 branch $MEDIA3'
        pushd media
        export MEDIA3_PATH="$PWD"
        export FFMPEG_MODULE_PATH="$PWD/libraries/decoder_ffmpeg/src/main"
        git checkout b930b40a16c06318e43c81771fa2b1024bdb3f29
        echo 'checkout b930b40a16c06318e43c81771fa2b1024bdb3f29'
        popd
        export HOST_PLATFORM="linux-x86_64"
        export ANDROID_ABI=23
        # export ENABLED_DECODERS=(vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd)
        export ENABLED_DECODERS=(alac aac)
        pushd $FFMPEG_MODULE_PATH/jni
        git clone -b $FFMPEG git://source.ffmpeg.org/ffmpeg
        export FFMPEG_PATH=$PWD/ffmpeg
        rm -rf /usr/local/bin/cmake
        ./build_ffmpeg.sh $FFMPEG_MODULE_PATH $NDK_PATH $HOST_PLATFORM $ANDROID_ABI ${ENABLED_DECODERS[@]}
        popd
        pushd $MEDIA3_PATH
        ./gradlew lib-decoder-ffmpeg:assembleRelease
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-ffmpeg-release.aar
        path: /media/libraries/decoder_ffmpeg/buildout/outputs/aar
